### PR TITLE
Removed Google + button

### PR DESCRIPTION
**Pull request by Pranav016**
### What is the change?
Removed the google + button

### What does it fix/add?
Solves #42 

### How was it tested?
On local host

## Submissions guide:
- [x] Have you followed the [Contribution guide](https://github.com/Neilblaze/Anyxz/blob/master/CONTRIBUTING.md)?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Neilblaze/Anyxz/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by Pranav016** [comment]
> ## This PR was made under NWoC
> ### What is the change?
> Removed the google + button
> 
> ### What does it fix/add?
> Solves #42
> 
> ### How was it tested?
> On local host
> 
> ## Submissions guide:
> * [x]  Have you followed the [Contribution guide](https://github.com/Neilblaze/Anyxz/blob/master/CONTRIBUTING.md)?
> * [x]  Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Neilblaze/Anyxz/pulls) for the same update/change?
> * [x]  Have you made corresponding changes to the documentation?
> * [x]  Your submission doesn't break any existing feature.
> * [x]  Have you lint your code locally prior to submission?

Good to merge? 😀 @Neilblaze

**Comment by Neilblaze** [comment]
Upstream the repo and then create the PR from a separate branch. I'm getting responsiveness issues.

**Comment by Pranav016** [comment]
> Upstream the repo and then create the PR from a separate branch. I'm getting responsiveness issues.

That's exactly what I did, made the PR from a new branch. Can you check again on a new browser/ device? Shouldn't give any issues though, otherwise I'll make a new PR

**Comment by Neilblaze** [comment]
> > Upstream the repo and then create the PR from a separate branch. I'm getting responsiveness issues.
> 
> That's exactly what I did, made the PR from a new branch. Can you check again on a new browser/ device? Shouldn't give any issues though, otherwise I'll make a new PR

You made the PR from another branch that's well & good, but did you upstream it?

**Comment by Pranav016** [comment]
> > > Upstream the repo and then create the PR from a separate branch. I'm getting responsiveness issues.
> > 
> > 
> > That's exactly what I did, made the PR from a new branch. Can you check again on a new browser/ device? Shouldn't give any issues though, otherwise I'll make a new PR
> 
> You made the PR from another branch that's well & good, but did you upstream it?

Did you mean pull from uptream? Then yes I updated my master before branching

**Comment by Pranav016** [comment]
I just checked on multiple devices, the currently deployed website and the one after my PR. I think the PR hasn't had any effect on responsiveness, looks the same to me, just the icon is removed! :p

**Comment by Neilblaze** [comment]
@Pranav016 do the upstream first, then raise the pr. Else you're good to go :+1:

**Pull request closed without merging**
