### PR TITLE
Solving issue:Add a share widget to the Project site #14

### PR DESCRIPTION
**Pull request by KerinPithawala**
1. Added sharing widgets of 3 social media: Facebook, Twitter and LinkedIn.
2. The URL of website: https://anyxz.vercel.app/ will be shared on these handles when user clicks on icons.

Before:
image

After:
image

This contribution is part of NWoC. Please review my pull request.

### CODE REVIEW

**Comment by Neilblaze** [comment]
Thanks for contributing @Kerveyfelix . But it needs a bit of aesthetic revamp. Can you make it like [this](https://www.quantumcloud.com/products/wp-content/uploads/2018/11/floating-social-share-icons.jpg)?

**Comment by KerinPithawala** [comment]
@Neilblaze Sure. I am researching how to do so.

**Comment by KerinPithawala** [comment]
Does this sharing widget look good? I couldn't make sharing like the one you shared for reference.
image

**Comment by Neilblaze** [comment]
Umm, like I believe it's consuming a lot of space over the `hero` section of the page. Choose a different design, a compact one.

**Comment by KerinPithawala** [comment]
image
This will work?

**Comment by Neilblaze** [comment]
I appreciate your hard work, but this isn't looking that great. Well, for now, you can do one thing, stack those social icons vertically & shift it to the left.

**Comment by KerinPithawala** [comment]
Sure. I am shifting the buttons to left and vertically arranging them as shown in the picture shared by you.
Actually I am not able to display buttons on the left side of that green color box. The buttons wherever, I pasted them are taking up entire horizontal axis. 

image
Should I push this to the repo?

**Comment by Neilblaze** [comment]
Can you upstream this branch & then show me the status, please?

**Comment by Kerveyfelix** [comment]
Sure. I am shifting the buttons to left and vertically arranging them as shown in the picture shared by you.
Actually I am not able to display buttons on the left side of that green color box. The buttons wherever, I pasted them are taking up entire horizontal axis. 

image
Should I push this to the repo?

**Comment by KerinPithawala** [comment]
Yes, I am trying to resolve the conflicts.

**Comment by Neilblaze** [comment]
Thank you @Kerveyfelix! Looks great, but just a tiny change is required before I merge your PR. All of the social icons need an upward shift inside those share buttons & also add a lil bit of space between those buttons, & you're good to go!

**Comment by KerinPithawala** [comment]
image
This works?

**Comment by Neilblaze** [comment]
@Kerveyfelix yup that looks better!

**Comment by KerinPithawala** [comment]
I have pushed the changes.

**Comment by Neilblaze** [comment]
@all-contributors please add @Kerveyfelix for code

**Comment by Neilblaze** [comment]
@all-contributors please add @Kerveyfelix for code

**Pull request merged**
