### PR TITLE
Made responsive

### PR DESCRIPTION
**Pull request by Nivedita967**
### What is the change?
Made this site responsive for mobile view.

### What does it fix/add?
Fixes issue #10 

## Submissions guide:
- [x] Have you followed the [Contribution guide](https://github.com/Neilblaze/Anyxz/blob/master/CONTRIBUTING.md)?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Neilblaze/Anyxz/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you lint your code locally prior to submission?

### Screenshots (if appropriate):
Screenshot (98)
Screenshot (99)

### CODE REVIEW

**Comment by Neilblaze** [comment]
Thanks for contributing @Nivedita967. I would like to suggest some changes to your work, but before that can you upstream your `feature` branch please? The recent addition of the dark mode toggle isn't being populated in the preview of your PR.

**Comment by Nivedita967** [comment]
please check once.

**Comment by Neilblaze** [comment]
Thank you @Nivedita967! Looks great, but just a tiny change is required before I merge your PR. For mobile view, update the following things,

- Center the `Anyxz` text, `New Background image + the color selector`, `Video capture`, `Image capture` & the `start recording` button.

**Comment by Nivedita967** [comment]
These are almost centered.

**Comment by Neilblaze** [comment]
Thank you @Nivedita967 for the updates. Looks better. Actually, I was saying that the `Anyxz` title is a bit left tilted in the responsive view. Nonetheless, I'm merging it!

**Comment by Neilblaze** [comment]
@all-contributors please add @Nivedita967 for code

**Comment by Nivedita967** [comment]
Thank You.

**Pull request merged**
